[loggers]
keys=root, mylogger, plugins, database

[handlers]
keys=consoleHandler, fileHandler

[formatters]
keys=consoleFormatter, fileFormatter

[logger_root]
# Root level ko WARNING kar diya hai taaki faltu logs na aayein
level=WARNING
handlers=consoleHandler, fileHandler

[logger_plugins]
qualname=plugins
level=WARNING
handlers=consoleHandler,fileHandler
propagate=0

[logger_database]
qualname=database
level=WARNING
handlers=consoleHandler,fileHandler
propagate=0

[logger_mylogger]
level=WARNING
handlers=consoleHandler, fileHandler
qualname=mylogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
# Console par sirf WARNING aur ERROR dikhayega (Render Fix)
level=WARNING
formatter=consoleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=ERROR
formatter=fileFormatter
args=('DreamXlogs.txt', 'w')

[formatter_consoleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%I:%M:%S %p

[formatter_fileFormatter]
format=[%(asctime)s:%(name)s:%(lineno)d:%(levelname)s] %(message)s
datefmt=%m/%d/%Y %I:%M:%S %p
